# Generated by Django 2.2.7 on 2020-01-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_id', models.IntegerField()),
                ('employe_name', models.CharField(max_length=100)),
                ('employe_email', models.EmailField(max_length=254)),
                ('employe_contact', models.CharField(max_length=15)),
                ('employe_address', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'costumer',
            },
        ),
    ]
