# Generated by Django 2.2.7 on 2020-01-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='Employee',
        ),
        migrations.AlterModelTable(
            name='employee',
            table=None,
        ),
    ]
